### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by thieflord06**
I need everyone to sign off on this

### CODE REVIEW

**Comment by thieflord06** [comment]
@j00bar @notque @suihanki @AshishDhama

**Comment by notque** [comment]
approved!

**Comment by AshishDhama** [comment]
@thieflord06 Is there a reason for not using the MIT license?

**Comment by thieflord06** [comment]
AGPLv3 is what was suggested, I would have to look into MIT.

**Comment by thieflord06** [comment]
@AshishDhama MIT allows companies to take the whole app and resell it without sharing the improvements they make back to the open source project.

**Review by notque — APPROVED** [review]
LGTM

**Comment by AshishDhama** [comment]
LGTM

**Comment by thieflord06** [comment]
@j00bar @suihanki

**Review by suihanki — APPROVED** [review]

**Review by j00bar — APPROVED** [review]
I consent to licensing my contributions under the AGPL v3. Thanks!

**Pull request merged**
